### ISSUE TITLE
Add possibility to export tasks assigned to different users.

### ISSUE THREAD

**Issue by Fischmax** [pablo127/asanaexporter#1]
First of all: Hello and thank you for your hard work.
However when using the command
java -jar asanaexporter-all-1.0.0.jar 0/082fd80a7b5003a08f94360e8f970391
I got this error:
 INFO [main] (Main.java:45) - Start importing tasks.
 INFO [main] (Main.java:50) - Imported 139 tasks in 3 s.
 INFO [main] (Main.java:53) - Start generate csv.
ERROR [main] (Main.java:57) - Error occurred while running AsanaExporter.
java.lang.RuntimeException: AssigneeId 575833230594161 is not equal to user id!
	at io.bitbucket.pablo127.asanaexporter.Main.getAssigneeName(Main.java:133)
	at io.bitbucket.pablo127.asanaexporter.Main.generateCsv(Main.java:87)
	at io.bitbucket.pablo127.asanaexporter.Main.main(Main.java:54)

The csv-file itself did not get created.
Any ideas? Thanks in advance.(:

**Comment by Fischmax** [comment]
So after getting the project to work in Eclipse and trying and looking around, I understand that it simply wasn't the project's purpose to export the names of different/multiple assignees.
I used the endpoint
"https://app.asana.com/api/1.0/workspaces/" + this.workspaceId + "/users"
to get the data I needed and just let the program read from a manually created map.
While the issue wasn't a bug, I might do it the right way and add a proper solution as a feature if I can find some time.

**Comment by pablo127** [comment]
Hi. It is really nice that you use the tool I created.
Exactly, you're right. I did not provide a possibility to export tasks assigned to different people.
It would be cool if you pull request that change as a feature. Would you like to do it?

**Comment by Fischmax** [comment]
Right now I'm a bit short on time, but yes - I would like to. (:

**Comment by philippeibach** [comment]
Hey, first thanks for this useful program :) 
however, when I run it, I end up with the same error messages than Fischmax. is there a workaround for non-developers? 
or is the program just for workspaces with only one team member?

**Comment by pablo127** [comment]
Hey. It is not possible right now to download tasks from different workspaces. I see the need for this feature but I do not have a resources (time) right now to develop this.

It is open source so actually anyone can develop it and pull request it.

**Comment by Fischmax** [comment]
I created a pull request for it.
