### ISSUE TITLE
Error during trying export

### ISSUE THREAD

**Issue by fredericocarneiro-hotmart** [pablo127/asanaexporter#12]
Hi there!
Thanks for sharing your code.
I´ve tried run it but I´m facing some problems.

I have an Asana project called "Backlog - DEV" but I wasnt able to download it. 
I´ve generated my personal token and run the following command line:

`C:\Downloads>java -jar asanaexporter-all-1.1.0.jar <MY_TOKEN> "Backlog - DEV"
 WARN [main] (Main.java:89) - Could not load lastModification.txt. All tasks will be downloaded.
ERROR [main] (Main.java:80) - Error occurred while running AsanaExporter.
java.lang.RuntimeException: Could not find workspace with name Backlog - DEV
        at io.bitbucket.pablo127.asanaexporter.UserDownloadCommand.lambda$run$1(UserDownloadCommand.java:54)
        at java.base/java.util.Optional.orElseThrow(Optional.java:401)
        at io.bitbucket.pablo127.asanaexporter.UserDownloadCommand.run(UserDownloadCommand.java:54)
        at io.bitbucket.pablo127.asanaexporter.Main.<init>(Main.java:210)
        at io.bitbucket.pablo127.asanaexporter.Main.main(Main.java:60)`

Could you help me?
Thanks.

**Comment by pablo127** [comment]
Hello :)
It is not possible to select project to export for now. You can select workspace in the way that you defined it. So in your case you should have `Backlog - DEV` workspace on your asana.
Here is more about workspaces, projects and so on: https://asana.com/guide/help/workspaces/basics
If you have more questions, please ask.

**Comment by fredericocarneiro-hotmart** [comment]
Great Pawel!
I tried now with my organization name and its working.

Thanks 😉

--
*Fred Carneiro*
Development manager
31 98868-2390
<http://www.hotmart.com/>



Em ter., 21 de jan. de 2020 às 13:05, Paweł Świderski <
notifications@github.com> escreveu:

**Comment by pablo127** [comment]
Great to hear that your problem was solved.
In case of any other problem please create `new issue`.
