### ISSUE TITLE
workspace: Object cannot be null

### ISSUE THREAD

**Issue by TowerBR** [pablo127/asanaexporter#6]
Hello Pawel,

I'm facing this message:
```
ERROR [pool-1-thread-1] (Requester.java:71) - Unexpected error occurred: {"errors":[{"message":"workspace: Object cannot be null","help":"For more information on API status codes and how to handle them, read the docs on errors: https://asana.com/developers/documentation/getting-started/errors"}]}
```

`"workspace: Object cannot be null"` => I couldn't identify any changes in their api regarding this.

Any idea?

Thanks!

**Comment by olegcarguy** [comment]
I'm getting the same error.

**Comment by pablo127** [comment]
Looks like there were some unexpected changes in Asana API.

I will look at this problem.

**Comment by TowerBR** [comment]
Thanks for the new release Pawel, works perfectly!

**Comment by olegcarguy** [comment]
Thank you Pawel!  Works great.

**Comment by pablo127** [comment]
Happy to hear that.
